version: build{build}

environment:
  ai_key:
    secure: 0uxsfE7N2HTcPQtM48XlcCDG1Lxf/xELs0S5GvnoGSDZWOkAJxukffyOOcuj1LGM
    
image: Visual Studio 2017

clone_folder: c:\dev\labrador-win-builder
clone_depth: 1

install:
  - ps: Start-FileDownload 'http://espotek.com/ai157.msi'
  - msiexec /i ai157.msi /qn
  - call "C:/Program Files (x86)/Caphyon/Advanced Installer 15.7/bin/x86/AdvancedInstaller.com" /register %ai_key%

build_script:
  - call "C:/Program Files (x86)/Caphyon/Advanced Installer 15.7/bin/x86/AdvancedInstaller.com" /rebuild Labrador.aip

artifacts:
  - path: Labrador-SetupFiles\Labrador_Installer.exe
    name: Labrador_Installer

deploy:
  tag: continuous-win32
  release: 'Continuous build (Windows)'
  description: 'Labrador Installer for Windows 7 or later (32-bit and 64-bit supported)'
  provider: GitHub
  auth_token:
      secure: DXAumCpZjJ3erz0OmBJybIJTwux9uSrdtqKtezd4wI9b2ELz3NELPwZfp+WfYKtb
  repository: EspoTek/Labrador
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
