version: build{build}

image: Visual Studio 2017

clone_folder: c:\dev\labrador-win-builder
clone_depth: 1

install:
  - ps: Start-FileDownload 'http://espotek.com/ai137.msi'
  - msiexec /ju ai137.msi /qn

build_script:
  - call "C:/Program Files (x86)/Caphyon/Advanced Installer 13.7/bin/x86/AdvancedInstaller.com" /rebuild Labrador.aip
