version: build{build}

environment:
  ai_key:
    secure: lGtLb+QcD8ePODVc6PQKXl2xcTbvPE3feqMG82EEY5Ca73tgFYoYlMAykSsrpO3c
  access_token:
    secure: DXAumCpZjJ3erz0OmBJybIJTwux9uSrdtqKtezd4wI9b2ELz3NELPwZfp+WfYKtb

image: Visual Studio 2017

clone_folder: c:\dev\labrador-win-builder
clone_depth: 1

install:
  - ps: Start-FileDownload 'http://espotek.com/ai137.msi'
  - msiexec /i ai137.msi /qn
  - call "C:/Program Files (x86)/Caphyon/Advanced Installer 13.7/bin/x86/AdvancedInstaller.com" /register %ai_key%

build_script:
  - call "C:/Program Files (x86)/Caphyon/Advanced Installer 13.7/bin/x86/AdvancedInstaller.com" /rebuild Labrador.aip

artifacts:
  - path: Labrador-SetupFiles\Labrador_Installer.exe
    name: Labrador_Installer

deploy:
  release: Labrador-v$(appveyor_build_version)
  description: 'Labrador Installer for Windows (32 and 64-bit)'
  provider: GitHub
  auth_token:
    secure: access_token
  repository: EspoTek/Labrador
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
